Args = --no-fallback \
       --initialize-at-build-time=org.slf4j \
       --initialize-at-build-time=org.slf4j.simple \
       --initialize-at-build-time=org.slf4j.impl \
       --initialize-at-run-time=org.eclipse.jgit \
       --initialize-at-run-time=org.eclipse.jgit.util.SystemReader \
       --initialize-at-run-time=org.eclipse.jgit.util.FS \
       -H:+ReportExceptionStackTraces \
       -H:IncludeResources=org/eclipse/jgit/.*\\.properties \
       -H:IncludeResourceBundles=org.eclipse.jgit.internal.JGitText
